name: salsa
channels:
  - bioconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - audioread=3.0.1=py311h38be061_1
  - blas=1.0=mkl
  - bottleneck=1.3.7=py311hf4808d0_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py311ha362b79_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2024.7.4=py311h06a4308_0
  - cffi=1.16.0=py311hb3a22ac_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.2.0=py311hdb19cb5_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - expat=2.6.2=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.13.1=py311h06a4308_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.51.0=py311h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2024.5.0=pyhff2d567_0
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.3.0=h59595ed_1
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h5py=3.11.0=py311h865a13c_0
  - hdf5=1.12.1=h2b7332f_3
  - icu=73.1=h6a678d5_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py311h06a4308_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.4=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h166bdaf_1003
  - lazy_loader=0.4=pyhd8ed1ab_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.5.147=0
  - libcurl=8.7.1=h251f7ec_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h77fa898_7
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - librosa=0.10.2.post1=pyhd8ed1ab_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hfdd30dd_2
  - lightning=2.2.5=pyhd8ed1ab_0
  - lightning-utilities=0.11.2=pyhd8ed1ab_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.42.0=py311h6a678d5_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py311h5eee18b_0
  - matplotlib=3.8.4=py311h06a4308_0
  - matplotlib-base=3.8.4=py311ha02d727_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpg123=1.32.6=h59595ed_0
  - mpmath=1.3.0=py311h06a4308_0
  - msgpack-python=1.0.8=py311h52f7536_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py311h06a4308_0
  - numba=0.59.1=py311h96b013e_0
  - numexpr=2.8.7=py311h65dcdc2_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.14=h5eee18b_0
  - pandas=2.2.1=py311ha02d727_0
  - pcre2=10.42=hebb0a14_1
  - pillow=10.3.0=py311h5eee18b_0
  - pip=24.0=py311h06a4308_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - ply=3.11=py311h06a4308_0
  - pooch=1.8.1=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pyparsing=3.0.9=py311h06a4308_0
  - pyqt=5.15.10=py311h6a678d5_0
  - pyqt5-sip=12.13.0=py311h5eee18b_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pysoundfile=0.12.1=pyhd8ed1ab_0
  - python=3.11.9=h955ad1f_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytorch=2.3.0=py3.11_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-lightning=2.2.2=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py311h06a4308_0
  - pyyaml=6.0.1=py311h5eee18b_0
  - qt-main=5.15.2=h53bd1ea_10
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=pyhd8ed1ab_0
  - scikit-learn=1.5.0=py311he08f58d_1
  - scipy=1.12.0=py311h08b1b3b_0
  - setuptools=69.5.1=py311h06a4308_0
  - sip=6.7.12=py311h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - soxr=0.1.3=h0b41bf4_3
  - soxr-python=0.3.7=py311h1f0f07a_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.12=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.3.0=py311_cu118
  - torchmetrics=1.4.0.post0=pyhd8ed1ab_0
  - torchtriton=2.3.0=py311
  - torchvision=0.18.0=py311_cu118
  - tornado=6.3.3=py311h5eee18b_0
  - tqdm=4.66.4=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py311h5eee18b_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wheel=0.43.0=py311h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zip=3.0=hd590300_3
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - chai-sacred==0.8.3
      - chardet==3.0.4
      - click==8.1.7
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - einops==0.8.0
      - gensim==4.3.2
      - gitdb==4.0.11
      - gitpython==3.1.43
      - googletrans==3.0.0
      - h11==0.9.0
      - h2==3.2.0
      - hpack==3.0.0
      - hstspreload==2024.6.1
      - httpcore==0.9.1
      - httpx==0.13.3
      - huggingface-hub==0.23.2
      - hyperframe==5.2.0
      - idna==2.10
      - jsonpickle==3.0.4
      - minimp3py==0.2.3
      - munch==2.5.0
      - nltk==3.8.1
      - packaging==24.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - regex==2024.5.15
      - rfc3986==1.5.0
      - safetensors==0.4.3
      - sentry-sdk==2.3.1
      - setproctitle==1.3.3
      - smart-open==7.0.4
      - smmap==5.0.1
      - sniffio==1.3.1
      - textaugment==1.3.4
      - textblob==0.17.1
      - timm==0.4.12
      - tokenizers==0.19.1
      - transformers==4.41.2
      - wandb==0.17.0
      - wrapt==1.16.0
prefix: /home/paul/miniconda3/envs/salsa
